name: demoApp
description: "My Demo App"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/app_icon.png"
  image_path_ios: "assets/icons/app_icon.png"
  background_color: "#5D5FEF"
  adaptive_icon_background: "#5D5FEF"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
